version: 2

shared: &shared
  steps:
    - checkout
    - restore_cache:
        keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-
    - run: composer install -n --prefer-dist
    - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
              - ./vendor
    - run: composer test
    - run: ./vendor/bin/php-coveralls -v


jobs:
  "php70":
    docker:
      - image: circleci/php:7.0-node-browsers
    <<: *shared
  "php71":
    docker:
      - image: circleci/php:7.1-node-browsers
    <<: *shared
  "php72":
    docker:
      - image: circleci/php:7.2-node-browsers
    <<: *shared
  "php73":
    docker:
      - image: circleci/php:7.3-node-browsers
    <<: *shared

workflows:
  version: 2
  build:
    jobs:
      - "php70"
      - "php71"
      - "php72"
      - "php73"
