version: 2

shared: &shared
  steps:
    - checkout
    - restore_cache:
      keys:
        # "composer.lock" can be used if it is committed to the repo
        - v1-dependencies-{{ checksum "composer.json" }}
        # fallback to using the latest cache if no exact match is found
        - v1-dependencies-
    - run: composer install -n --prefer-dist
    - save_cache:
        key: v1-dependencies-{{ checksum "composer.json" }}
        paths:
          - ./vendor
    - run: ./vendor/bin/phpunit


jobs:
  "php70":
    docker:
      - image: circleci/php:7.0-node-browsers
    <<: *shared
  "php71":
    docker:
      - image: circleci/php:7.1-node-browsers
    <<: *shared
  "php72":
    docker:
      - image: circleci/php:7.2-node-browsers
    <<: *shared
  "php73":
    docker:
      - image: circleci/php:7.3-node-browsers
    <<: *shared
