name: Test
on:
  - push
  - pull_request

jobs:
  test:
    name: Run tests
    runs-on: 'ubuntu-20.04'
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
        symfony-version:
          - "5"
          - "6"
          - "7"
        exclude:
          - php-version: 7.3
            symfony-version: 7
          - php-version: 7.4
            symfony-version: 7
          - php-version: 8.0
            symfony-version: 7
          - php-version: 8.1
            symfony-version: 7
          - php-version: 7.3
            symfony-version: 6
          - php-version: 7.4
            symfony-version: 6
    steps:
      - name: Dump matrix context
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Dump composer verson
        run: composer --version

      - name: Validate composer.json
        run: composer --verbose validate

      - name: Install dependencies
        run: |
          composer require symfony/console:^${{ matrix.symfony-version }}.0 symfony/dependency-injection:^${{ matrix.symfony-version }}.0 symfony/process:^${{ matrix.symfony-version }}.0
          git checkout .
          composer update not-installed/here

      - name: Run phpstan
        run: composer phpstan

      - name: Run tests
        run: composer test

      - name: Coveralls
        if: matrix.php-version == 7.4
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          php vendor/bin/php-coveralls -v
